# Run on commit to the master branch (After PR is merged)
name: Lint and Test

on:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    # Step 3: set thresholds for pylint and coverage
    - name: Set up thresholds
      id: thresholds
      run: |
        echo "pylint_threshold=9.95" >> $GITHUB_OUTPUT
        echo "coverage_threshold=90" >> $GITHUB_OUTPUT

    # Step 4: Install dependencies (including Anybadge)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install -r app/test/requirements.txt

  # ---------- PYLINT ---------- #
    # Step 5: Run pylint and calculate the score
    - name: Run pylint
      id: pylint_run
      run: |
        pylint_score=$(pylint app --fail-under=${{ steps.thresholds.outputs.pylint_threshold }} --rcfile=app/.pylintrc --output-format=parseable | tee reports/pylint.txt | awk '/Your code has been rated at/ {print $7}' | sed 's/\/10//')
        pylint_score=$(echo "$pylint_score" | xargs)  # Ensure no leading/trailing whitespace
        echo "Pylint score is: $pylint_score/10"
        echo "pylint_score=$pylint_score" >> $GITHUB_OUTPUT
        if [ $(echo "$pylint_score < ${{ steps.thresholds.outputs.pylint_threshold }}" | bc -l) -eq 1 ]; then
          exit 1
        fi
      continue-on-error: true  # Do not fail the job yet

    # Step 6: Generate PyLint Badge
    - name: Generate PyLint Badge
      id: pylint_generate
      run: |
        if [ "${{ steps.pylint_run.outcome }}" == "failure" ]; then
          echo "FAIL"
          anybadge -l PyLint -v ${{ steps.pylint_run.outputs.pylint_score }} -s /10 -f img/pylint_badge.svg -o -c red
        elif [ "${{ steps.pylint_run.outcome }}" == "success" ]; then
          echo "PASS"
          anybadge -l PyLint -v ${{ steps.pylint_run.outputs.pylint_score }} -s /10 -f img/pylint_badge.svg -o pylint
        fi

  # ---------- PYTEST ---------- #
    # Step 7: Run Coverage and generate PyTest report
    - name: Run PyTest with Coverage
      id: pytest_run
      run: |
        coverage run -m pytest --tb=no --md-report --md-report-output=reports/pytest.md
      continue-on-error: true  # Do not fail the job yet

    # Step 8: Generate PyTest Badge
    - name: Generate PyTest Badge
      id: pytest_generate
      run: |
        if [ "${{ steps.pytest_run.outcome }}" == "failure" ]; then
          echo "FAIL"
          anybadge -l PyTest -v FAIL -f img/pytest_badge.svg -o -c red
        elif [ "${{ steps.pytest_run.outcome }}" == "success" ]; then
          echo "PASS"
          anybadge -l PyTest -v PASS -f img/pytest_badge.svg -o -c green
        fi

  # ---------- COVERAGE ---------- #
    # Step 9: Check coverage and generate Coverage report
    - name: Check coverage
      id: coverage_run
      run: |
        coverage_percentage=$(coverage report | tee reports/coverage.txt | grep 'TOTAL' | awk '{print $4}' | sed 's/%//')
        echo "Coverage percentage is: $coverage_percentage"
        echo "coverage_percentage=$coverage_percentage" >> $GITHUB_OUTPUT
        coverage report --fail-under=${{ steps.thresholds.outputs.coverage_threshold }}
      continue-on-error: true  # Do not fail the job yet

    # Step 10: Generate Coverage Badge
    - name: Generate Coverage Badge
      id: coverage_generate
      run: |
        if [ "${{ steps.coverage_run.outcome }}" == "failure" ]; then
          echo "FAIL"
          anybadge -l Coverage -v ${{ steps.coverage_run.outputs.coverage_percentage }} -s% -f img/coverage_badge.svg -o -c red
        elif [ "${{ steps.coverage_run.outcome }}" == "success" ]; then
          echo "PASS"
          anybadge -l Coverage -v ${{ steps.coverage_run.outputs.coverage_percentage }} -f img/coverage_badge.svg -o coverage
        fi

  # ---------- Check Versions ---------- #
    # Not needed as checked on PR creation

  # ---------- UPLOAD ---------- #
    # Step 11: Upload the badges and reports as GitHub artifacts (optional)
    - name: Upload badges an reports
      uses: actions/upload-artifact@v4
      with:
        name: badges-and-reports
        path: |
          img/pylint_badge.svg
          img/pytest_badge.svg
          img/coverage_badge.svg
          reports/pylint.txt
          reports/pytest.md
          reports/coverage.txt

    # Step 12: Commit the badges to the repo if you want them automatically updated
    - name: Commit badges
      id: commit_badges
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add img/pylint_badge.svg img/coverage_badge.svg img/pytest_badge.svg reports/pylint.txt reports/coverage.txt reports/pytest.md
        git commit -m "Update badges & reports"
        git push
      continue-on-error: true

    # Step 13: Fail if the tests Failed
    - name: Check Test Result
      if: steps.coverage_run.outcome == 'failure' || steps.pylint_run.outcome == 'failure' || steps.pytest_run.outcome == 'failure'
      run: |
        if [ "${{ steps.pylint_run.outcome }}" == "failure" ]; then
          echo "PyLint Failed"
        fi
        if [ "${{ steps.pytest_run.outcome }}" == "failure" ]; then
          echo "PyTest Failed"
        fi
        if [ "${{ steps.coverage_run.outcome }}" == "failure" ]; then
          echo "Coverage Failed"
        fi
        exit 1