name: Sync README with Docker Hub

on:
  push:
    branches:
      - master # Trigger only on the master branch
    paths:
      - 'README.md' # Trigger only when README.md changes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Update README on Docker Hub
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          # Read the README.md content
          README_CONTENT=$(cat README.md)

          # Replace special characters (JSON escaping)
          ESCAPED_CONTENT=$(echo "$README_CONTENT" | jq -Rsa .)

          # Update the Docker Hub repository description
          curl -s -o /dev/null -w "%{http_code}" \
            -X PATCH "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/user-manager/" \
            -H "Authorization: Bearer ${{ secrets.DOCKER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"full_description\": $ESCAPED_CONTENT}" || exit 1
